export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FETCH_FULL_POST_START = 'FETCH_FULL_POST_START';
export const FETCH_FULL_POST_SUCCESS = 'FETCH_FULL_POST_SUCCESS';
export const FETCH_FULL_POST_FAIL = 'FETCH_FULL_POST_FAIL';

export const FETCH_ANSWERS_START = 'FETCH_ANSWERS_START';
export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_FAIL = 'FETCH_ANSWERS_FAIL';
